runOn:
    - minServerVersion: "4.3.x"
      topology: ["replicaset", "sharded"]

data:
    - { _id: 1, x: 11 }
    - { _id: 2, x: 22 }

tests:
    - description: "FindOneAndUpdate succeeds after RetryableWriteError from server"
      failPoint:
          configureFailPoint: failCommand
          mode: { times: 1 }
          data:
              failCommands: ["findAndModify"]
              errorLabels: ["RetryableWriteError"]
              errorCode: 112 # WriteConflict, not a retryable error code
      operation:
          name: "findOneAndUpdate"
          arguments:
              filter: { _id: 1 }
              update: { $inc: { x: 1 } }
              returnDocument: "Before"
      outcome:
          result: { _id: 1, x: 11 }
          collection:
              data:
                  - { _id: 1, x: 12 }
                  - { _id: 2, x: 22 }

    - description: "FindOneAndUpdate fails if server does not return RetryableWriteError"
      failPoint:
          configureFailPoint: failCommand
          mode: { times: 1 }
          data:
              failCommands: ["findAndModify"]
              errorLabels: []
              errorCode: 11600 # InterruptedAtShutdown, normally a retryable error code
      operation:
          name: "findOneAndUpdate"
          arguments:
              filter: { _id: 1 }
              update: { $inc: { x: 1 } }
              returnDocument: "Before"
      outcome:
          error: true
          result:
              errorLabelsOmit: ["RetryableWriteError"]
          collection:
              data:
                  - { _id: 1, x: 12 }
                  - { _id: 2, x: 22 }
