runOn:
    - minServerVersion: "4.3.x"
      topology: ["replicaset", "sharded"]

data: []

tests:
    - description: "InsertOne succeeds after RetryableWriteError from server"
      failPoint:
          configureFailPoint: failCommand
          mode: { times: 1 }
          data:
              failCommands: ["insert"]
              errorLabels: ["RetryableWriteError"]
              errorCode: 112 # WriteConflict, not a retryable error code
          operation:
              name: "insertOne"
              arguments:
                  document: { _id: 1, x: 11 }
          outcome:
              result:
                  insertedId: 1
              collection:
                  data:
                      - { _id: 1, x: 11 }
