runOn:
    # TODO: Update once SERVER-41245 is released
    - minServerVersion: "4.3.x"
      topology: ["replicaset", "sharded"]

data:
    - { _id: 1, x: 11 }

tests:
    - description: "InsertMany succeeds after RetryableWriteError from server"
      failPoint:
          configureFailPoint: failCommand
          mode: { times: 1 }
          data:
              failCommands: ["insert"]
              errorLabels: ["RetryableWriteError"]
              errorCode: 112 # WriteConflict, not a retryable error code
      operation:
          name: "insertMany"
          arguments:
              documents:
                  - { _id: 2, x: 22 }
                  - { _id: 3, x: 33 }
              options: { ordered: true }
      outcome:
          result:
              insertedIds: { 0: 2, 1: 3 }
          collection:
              data:
                  - { _id: 1, x: 11 }
                  - { _id: 2, x: 22 }
                  - { _id: 3, x: 33 }

    - description: "InsertMany fails if server does not return RetryableWriteError"
      failPoint:
          configureFailPoint: failCommand
          mode: { times: 1 }
          data:
              failCommands: ["insert"]
              errorLabels: []
              errorCode: 11600 # InterruptedAtShutdown, normally a retryable error code
      operation:
          name: "insertMany"
          arguments:
              documents:
                  - { _id: 2, x: 22 }
                  - { _id: 3, x: 33 }
              options: { ordered: true }
      outcome:
          error: true
          result:
              errorLabelsOmit: ["RetryableWriteError"]
          collection:
              data:
                  - { _id: 1, x: 11 }
